[workspace]
members = [
  "crates/orchestrate-nexus",
  "crates/orchestrate",
  "crates/orchestrate-meta",
]
resolver = "3"

[workspace.package]
version = "0.31.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LiGoldragon/orchestrate"
publish = false

[workspace.dependencies]
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec.git", rev = "f2cc06858d38a4028c928d33323a6d682e7c222f" }
ethos-zero = { git = "https://github.com/LiGoldragon/ethos-zero.git", rev = "4695ee0c1f5d00dcf5cceba08f5fa00412b92184" }
meta-signal-orchestrate = { path = "/git/github.com/LiGoldragon/meta-signal-orchestrate", default-features = false }
protos = { git = "https://github.com/LiGoldragon/protos.git", rev = "b543678cfc8609529cea7174eb4af8a64daa54ad" }
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
sema-engine = { git = "https://github.com/LiGoldragon/sema-engine.git", rev = "7158e5503f37fd2fbca1d707f134e38a3fda1176" }
signal-orchestrate = { path = "/git/github.com/LiGoldragon/signal-orchestrate", default-features = false }
nexus = { git = "https://github.com/LiGoldragon/nexus", rev = "a84bfa960c0d5c02d30048c4bbbc67dfef79a67c" }
kameo = "0.20"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "warn", priority = -1 }
dead_code = "warn"
