// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::Input as OrdinaryInput;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::Output as OrdinaryOutput;
#[rustfmt::skip]
pub use meta_signal_orchestrate::schema::lib::Input as MetaInput;
#[rustfmt::skip]
pub use meta_signal_orchestrate::schema::lib::Output as MetaOutput;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::RoleSnapshot as RoleSnapshot;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::LanesObserved as LanesObserved;
#[rustfmt::skip]
pub use signal_orchestrate::schema::lib::ActivityList as ActivityList;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    ReadRoles(ReadRoles),
    ReadLanes(ReadLanes),
    ReadActivity(ReadActivity),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadRoles {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadLanes {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadActivity {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    RolesRead(RoleSnapshot),
    LanesRead(LanesObserved),
    ActivityRead(ActivityList),
    ReadMiss(ReadMiss),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadMiss(ReadMissReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadMissReason {
    NotFound,
    NotBuiltYet,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    ApplyOrdinary(ApplyOrdinary),
    ApplyMeta(ApplyMeta),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplyOrdinary(OrdinaryInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplyMeta(MetaInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    OrdinaryApplied(OrdinaryOutput),
    MetaApplied(MetaOutput),
    WriteRejected(WriteRejected),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WriteRejected(WriteRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteRejectionReason {
    Conflict,
    InvalidOperation,
    DependencyUnavailable,
    NotBuiltYet,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

#[rustfmt::skip]
impl ReadMiss {
    pub fn new(payload: ReadMissReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReadMissReason {
        &self.0
    }
    pub fn into_payload(self) -> ReadMissReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReadMissReason> for ReadMiss {
    fn from(payload: ReadMissReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplyOrdinary {
    pub fn new(payload: OrdinaryInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OrdinaryInput {
        &self.0
    }
    pub fn into_payload(self) -> OrdinaryInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<OrdinaryInput> for ApplyOrdinary {
    fn from(payload: OrdinaryInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplyMeta {
    pub fn new(payload: MetaInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MetaInput {
        &self.0
    }
    pub fn into_payload(self) -> MetaInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<MetaInput> for ApplyMeta {
    fn from(payload: MetaInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WriteRejected {
    pub fn new(payload: WriteRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WriteRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> WriteRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<WriteRejectionReason> for WriteRejected {
    fn from(payload: WriteRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn read_roles(payload: ReadRoles) -> Self {
        Self::ReadRoles(payload)
    }
    pub fn read_lanes(payload: ReadLanes) -> Self {
        Self::ReadLanes(payload)
    }
    pub fn read_activity(payload: ReadActivity) -> Self {
        Self::ReadActivity(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn roles_read(payload: RoleSnapshot) -> Self {
        Self::RolesRead(payload)
    }
    pub fn lanes_read(payload: LanesObserved) -> Self {
        Self::LanesRead(payload)
    }
    pub fn activity_read(payload: ActivityList) -> Self {
        Self::ActivityRead(payload)
    }
    pub fn read_miss(payload: ReadMissReason) -> Self {
        Self::ReadMiss(ReadMiss::new(payload))
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn apply_ordinary(payload: OrdinaryInput) -> Self {
        Self::ApplyOrdinary(ApplyOrdinary::new(payload))
    }
    pub fn apply_meta(payload: MetaInput) -> Self {
        Self::ApplyMeta(ApplyMeta::new(payload))
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn ordinary_applied(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryApplied(payload)
    }
    pub fn meta_applied(payload: MetaOutput) -> Self {
        Self::MetaApplied(payload)
    }
    pub fn write_rejected(payload: WriteRejectionReason) -> Self {
        Self::WriteRejected(WriteRejected::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadRoles> for SemaReadInput {
    fn from(payload: ReadRoles) -> Self {
        Self::ReadRoles(payload)
    }
}

#[rustfmt::skip]
impl From<ReadLanes> for SemaReadInput {
    fn from(payload: ReadLanes) -> Self {
        Self::ReadLanes(payload)
    }
}

#[rustfmt::skip]
impl From<ReadActivity> for SemaReadInput {
    fn from(payload: ReadActivity) -> Self {
        Self::ReadActivity(payload)
    }
}

#[rustfmt::skip]
impl From<RoleSnapshot> for SemaReadOutput {
    fn from(payload: RoleSnapshot) -> Self {
        Self::RolesRead(payload)
    }
}

#[rustfmt::skip]
impl From<LanesObserved> for SemaReadOutput {
    fn from(payload: LanesObserved) -> Self {
        Self::LanesRead(payload)
    }
}

#[rustfmt::skip]
impl From<ActivityList> for SemaReadOutput {
    fn from(payload: ActivityList) -> Self {
        Self::ActivityRead(payload)
    }
}

#[rustfmt::skip]
impl From<ReadMiss> for SemaReadOutput {
    fn from(payload: ReadMiss) -> Self {
        Self::ReadMiss(payload)
    }
}

#[rustfmt::skip]
impl From<ApplyOrdinary> for SemaWriteInput {
    fn from(payload: ApplyOrdinary) -> Self {
        Self::ApplyOrdinary(payload)
    }
}

#[rustfmt::skip]
impl From<ApplyMeta> for SemaWriteInput {
    fn from(payload: ApplyMeta) -> Self {
        Self::ApplyMeta(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryOutput> for SemaWriteOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryApplied(payload)
    }
}

#[rustfmt::skip]
impl From<MetaOutput> for SemaWriteOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaApplied(payload)
    }
}

#[rustfmt::skip]
impl From<WriteRejected> for SemaWriteOutput {
    fn from(payload: WriteRejected) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadInputRoute {
    ReadRoles,
    ReadLanes,
    ReadActivity,
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::ReadRoles(_) => SemaReadInputRoute::ReadRoles,
            Self::ReadLanes(_) => SemaReadInputRoute::ReadLanes,
            Self::ReadActivity(_) => SemaReadInputRoute::ReadActivity,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadOutputRoute {
    RolesRead,
    LanesRead,
    ActivityRead,
    ReadMiss,
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::RolesRead(_) => SemaReadOutputRoute::RolesRead,
            Self::LanesRead(_) => SemaReadOutputRoute::LanesRead,
            Self::ActivityRead(_) => SemaReadOutputRoute::ActivityRead,
            Self::ReadMiss(_) => SemaReadOutputRoute::ReadMiss,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteInputRoute {
    ApplyOrdinary,
    ApplyMeta,
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::ApplyOrdinary(_) => SemaWriteInputRoute::ApplyOrdinary,
            Self::ApplyMeta(_) => SemaWriteInputRoute::ApplyMeta,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteOutputRoute {
    OrdinaryApplied,
    MetaApplied,
    WriteRejected,
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::OrdinaryApplied(_) => SemaWriteOutputRoute::OrdinaryApplied,
            Self::MetaApplied(_) => SemaWriteOutputRoute::MetaApplied,
            Self::WriteRejected(_) => SemaWriteOutputRoute::WriteRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    SemaWriteInputRoute::ApplyOrdinary => "SemaWriteInputApplyOrdinary",
                    SemaWriteInputRoute::ApplyMeta => "SemaWriteInputApplyMeta",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    SemaReadInputRoute::ReadRoles => "SemaReadInputReadRoles",
                    SemaReadInputRoute::ReadLanes => "SemaReadInputReadLanes",
                    SemaReadInputRoute::ReadActivity => "SemaReadInputReadActivity",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    SemaWriteOutputRoute::OrdinaryApplied => {
                        "SemaWriteOutputOrdinaryApplied"
                    }
                    SemaWriteOutputRoute::MetaApplied => "SemaWriteOutputMetaApplied",
                    SemaWriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    SemaReadOutputRoute::RolesRead => "SemaReadOutputRolesRead",
                    SemaReadOutputRoute::LanesRead => "SemaReadOutputLanesRead",
                    SemaReadOutputRoute::ActivityRead => "SemaReadOutputActivityRead",
                    SemaReadOutputRoute::ReadMiss => "SemaReadOutputReadMiss",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for SemaWriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for SemaReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
